server:
  port: 80

spring:
  application:
    name: cloud-order-service
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*  # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.0.* # 优先使用 192.168.0.*

eureka:
  client:
    #true表示将自己注册进eureka server
    register-with-eureka: true
    #true默认值,从eureka server抓取已有的注册信息,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  #配置主机名称
  instance:
    instance-id: consumerorder80
    prefer-ip-address: true