server:
  port: 9003

spring:
  application:
    name: provider-payment9003-9004

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.201.128:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
