server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址(linux)
        server-addr: 192.168.201.128:1111
    sentinel:
      transport:
        #配置sentinel dashboard也址
        dashboard: localhost:8080
        #认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      #        nacos流控规则持久化,在nacos上配置规则文件
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.201.128:1111
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true