server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  #路由匹配规则
  cloud:
    gateway:
      routes:
        - id: payment-routh                #路由的id，没有固定规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001       #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #负载均衡，匹配后提供服务的路由地址
          filters:
            - AddRequestHeader=X-Request-Id, 1024
          predicates: #Predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理。
            - Path=/payment/get/**         #断言，路径相匹配的进行路由
            - After=2021-07-27T14:43:15.366+08:00[Asia/Shanghai]   #在此时间之后，访问这个接口才有效  时间级别的还有Before，Between
            #- Cookie=username,haoyong        #cookie级别的路由规则
            #- Header=X-Request-Id, \d+       #请求头要有X-Request-Id属性，并且值为整数的正则表达式
            # - Method=Get                     #  请求方法方式

        - id: payment-routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true                #开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
