# 单个eureka
#server:
#  port: 7001
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#  集群
spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*  # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.0.* # 优先使用 192.168.0.*

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    registerWithEureka: false
    #false表示自己就是注册中心职责是维护服务实例,不需要检索服务
    fetchRegistry: false
    serviceUrl:
      #单机版
      #defaultZone: http://eureka7001.com:7001/eureka/
      #http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  server:
    #关闭eureka的自我保护机制,保证不可用服务被及时剔除
    enable-self-preservation: false
    #eureka server清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 2000