server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com    #eureka服务端实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心职责是维护服务实例,不需要检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - VMware.*  # 忽略虚拟机网卡
      use-only-site-local-interfaces: true
      preferred-networks: 192.168.0.* # 优先使用 192.168.0.*
