server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    #true默认值,从eureka server抓取已有的注册信息,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#开启服务降级
feign:
  hystrix:
    enabled: true